pipeline {
  agent none
  stages {
    // stage('Test') {
    //   agent {
    //     docker {
    //       image 'qnib/pytest'
    //     }
    //   }
    //   steps {
    //     sh 'py.test --verbose --junit-xml tests/results.xml chatbot/chat.py'
    //   }
    //   post {
    //     always {
    //       junit 'tests/results.xml'
    //     }
    //   }
    // }
    stage('Build') {
      agent any
      steps {
        sh 'docker build -t ccawmu .'
      }
    }
  }
  post {
    success {
      sh 'docker run ccawmu:latest'
    }
  }
}